### ISSUE TITLE
How to config and build game for iOS

### ISSUE THREAD

**Issue by takaaptech** [gmhevinci/MotionFramework-Demo#1]
Hi @gmhevinci 
Could you please add some simple note on how to config and build game for iOS platform?
Thank you so muh!
I am trying to switch platform to iOS and press build on AssetBundle Builder, then export the demo, when run on xCode i have this error:

Failed to download web data : file:///private/var/containers/Bundle/Application/33E5C3AF-02E4-4E73-B5E4-E1CF8B2F8289/gametest.app/Data/Raw/PatchManifest.bytes Error : HTTP/1.1 404 Not Found
System.Action`2:Invoke(T1, T2)
MotionFramework.Network.<DownLoad>d__1:MoveNext()
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
 
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)

Exception: Fatal error : Failed download file : file:///private/var/containers/Bundle/Application/33E5C3AF-02E4-4E73-B5E4-E1CF8B2F8289/gametest.app/Data/Raw/PatchManifest.bytes
  at MotionFramework.Patch.LocalBundleServices+<InitializeAsync>d__4.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

**Comment by takaaptech** [comment]
I just try again by pressing three buttons after changing the Platform to iOS and can build and run.
Thank so much!

**Comment by gmhevinci** [comment]
If the PatchManifest.bytes is not found, please make sure it is included in the StreammingAssets folder.
