### ISSUE TITLE
Question on AssetBundleCollector

### ISSUE THREAD

**Issue by takaaptech** [gmhevinci/MotionFramework-Demo#3]
Hi @gmhevinci 
I just a newbie in Asset Bundle so please help me some question

Why we have many assets in the GameArt folder but we only put the Sprite folder into AssetBundleCollector?

And from the demo project, I see all the sprite from Sprite foder just put into atlas locate at GameRes/UIAtlas. So why we need to put those sprites into AssetBundleCollector again?

What is the common rule for us to put the assets into AssetBundleCollector?

Thank you so much! I am learning the MotionFramework day by day and I already read the tutorial from here
https://github.com/gmhevinci/MotionFramework/blob/master/Docs/Editor.AssetBundleCollector.md
But still can not figure it out.

![image](https://user-images.githubusercontent.com/6276251/114151454-530caf00-9947-11eb-8152-ff9d35e90292.png)

**Comment by gmhevinci** [comment]
1. So why we need to put those sprites into AssetBundleCollector again?
We want to put all the Sprites into one assetbundle file. The purpose of this is to prevent the Sprite object from being package into the ui panel
我们希望将精灵对象打进一个AssetBundle文件里，这样可以避免精灵对象打进依赖的UI面板里，造成资源冗余。

2. What is the common rule for us to put the assets into AssetBundleCollector?
The resources that the code calls need to be collected and sprites object need collected.
需要主动收集的资源主要包括代码主动加载的所有资源对象，例如：场景对象，UI面板预制体，模型预制体，图集，音频，配表等。还有上面所述的精灵对象需要主动收集。

**Comment by takaaptech** [comment]
@gmhevinci Thank you so much now I can understand what should be collected into AssetBundleCollector.

I have one question: Why we still need to put Sprites into the asset bundle, we already put the sprite atlas (That contain the sprites) into the assetbundle? I think the build output only contains sprite atlas, not the separate sprites?

**Comment by gmhevinci** [comment]
If you use unity sprite atlas system, these sprites are also referenced by the atlas.
如果你使用了Unity的新的图集系统，那么这些精灵对象也会被图集引用。MF的资源框架会把每个精灵对象单独生成一个AB文件，但是我们不希望这样做，所以主动把文件夹内的所有精灵对象打到一个AB文件里。

**Comment by takaaptech** [comment]
Thank you so much!
