### ISSUE TITLE
请问如何运行啊

### ISSUE THREAD

**Issue by huhuang03** [gmhevinci/MotionFramework-Demo#4]
我是一个Unity新手
我按照步骤解压了Framework.zip
然后使用untiy打开

怎么出现README里面的截图呢
![image](https://github.com/gmhevinci/Demo1/raw/master/Docs/Image/img2.png)

我只能出现：
![image](https://user-images.githubusercontent.com/4716706/188992347-b7c9b7db-023e-4491-b99a-e6a2814bb227.png)

如果选择Asserts/GameRes/Scene/Town的话。为这个：
![image](https://user-images.githubusercontent.com/4716706/188993415-27ccd317-44c8-498f-af25-42ea43665132.png)

**Comment by gmhevinci** [comment]
打开Boot场景，然后运行游戏。
